/**
 * HtmlSourceCleanup
 * 职责：清洗 LLM 生成的 HTML 输出，确保符合平台约束
 * 基于 Ironsmith ContentViewSourceCleanup 的启发
 * 纯代码规则，100% 确定性
 */

export interface CleanupResult {
  html: string
  preview: string
  issues: string[]
  wasModified: boolean
}

export function cleanupHtmlSource(rawHtml: string, name: string): CleanupResult {
  let html = rawHtml
  const issues: string[] = []
  let wasModified = false

  // 1. 剥离 Markdown 围栏 (```html ... ```)
  const fenceMatch = html.match(/```(?:html)?\s*([\s\S]*?)\s*```/)
  if (fenceMatch) {
    html = fenceMatch[1].trim()
    issues.push('Removed markdown fence')
    wasModified = true
  }

  // 2. 剥离 think 块 (reasoning 模型的思考过程)
  const thinkPatterns = [
    /\s*<think>[\s\S]*?<\/think>\s*/gi,
    /\n?Thinking:[\s\S]*?(?=\n\n|<\w|<!)/i,
    /\n?Let me think[\s\S]*?(?=\n\n|<\w|<!)/i,
    /\n?I need to[\s\S]*?(?=\n\n|<\w|<!)/i,
  ]
  for (const pattern of thinkPatterns) {
    if (pattern.test(html)) {
      html = html.replace(pattern, '')
      issues.push('Removed think/reasoning block')
      wasModified = true
    }
  }

  // 3. 移除 <html>, <head>, <body> 标签 (平台提供)
  // 保留 body 内的内容
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  if (bodyMatch) {
    html = bodyMatch[1].trim()
    issues.push('Extracted body content (removed html/head/body tags)')
    wasModified = true
  }

  // 4. 移除 <DOCTYPE>, <html>, <head> 标签 (如果 body 提取失败)
  const doctypeRemoved = html.replace(/<!DOCTYPE[^>]*>/gi, '')
  if (doctypeRemoved !== html) {
    html = doctypeRemoved
    issues.push('Removed DOCTYPE declaration')
    wasModified = true
  }
  const htmlTagRemoved = html.replace(/<html[^>]*>[\s\S]*?<\/html>/gi, (match) => {
    // Extract body content from within html tag
    const bodyInHtml = match.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
    return bodyInHtml ? bodyInHtml[1] : match
  })
  if (htmlTagRemoved !== html) {
    html = htmlTagRemoved
    issues.push('Removed html tag wrapper')
    wasModified = true
  }
  const headRemoved = html.replace(/<head[^>]*>[\s\S]*?<\/head>/gi, '')
  if (headRemoved !== html) {
    html = headRemoved
    issues.push('Removed head tag')
    wasModified = true
  }
  const bodyTagRemoved = html.replace(/<\/?body[^>]*>/gi, '')
  if (bodyTagRemoved !== html) {
    html = bodyTagRemoved
    issues.push('Removed body tag wrappers')
    wasModified = true
  }

  // 5. 移除外部 CSS 链接 (平台提供 Tailwind)
  const linkRemoved = html.replace(/<link[^>]*rel=["']stylesheet["'][^>]*>/gi, '')
  if (linkRemoved !== html) {
    html = linkRemoved
    issues.push('Removed external CSS links')
    wasModified = true
  }

  // 6. 移除外部 JS 引用 (script src)
  // 保留内联 <script>...</script>
  const externalScriptRemoved = html.replace(/<script\s+[^>]*src=["'][^"']*["'][^>]*>[\s\S]*?<\/script>/gi, '')
  if (externalScriptRemoved !== html) {
    html = externalScriptRemoved
    issues.push('Removed external script references')
    wasModified = true
  }

  // 7. 移除 <meta>, <title>, <base> 标签 (平台提供)
  const metaRemoved = html.replace(/<meta[^>]*>/gi, '')
  if (metaRemoved !== html) {
    html = metaRemoved
    issues.push('Removed meta tags')
    wasModified = true
  }
  const titleRemoved = html.replace(/<title>[\s\S]*?<\/title>/gi, '')
  if (titleRemoved !== html) {
    html = titleRemoved
    issues.push('Removed title tag')
    wasModified = true
  }
  const baseRemoved = html.replace(/<base[^>]*>/gi, '')
  if (baseRemoved !== html) {
    html = baseRemoved
    issues.push('Removed base tag')
    wasModified = true
  }

  // 8. 移除危险属性 (onclick with eval, etc.)
  const dangerousRemoved = html.replace(/\son\w+=["']\s*eval\s*\([^)]*\)["']/gi, '')
  if (dangerousRemoved !== html) {
    html = dangerousRemoved
    issues.push('Removed dangerous eval attributes')
    wasModified = true
  }

  // 9. 清理多余的空白行
  html = html.replace(/\n{3,}/g, '\n\n').trim()

  // 10. 确保 HTML 不是空的
  if (!html.trim()) {
    html = `<div class="p-8 text-center">
  <h1 class="text-2xl font-bold mb-4">${name || 'Generated App'}</h1>
  <p class="text-muted-foreground">This app was generated by AI.</p>
</div>`
    issues.push('HTML was empty after cleanup, generated fallback')
    wasModified = true
  }

  // 11. 提取 preview (body 内的内容，用于 iframe 预览)
  // 移除内联 <script> 和 <style> 块用于 preview，保留在完整 HTML 中
  const preview = html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .trim()

  return { html, preview, issues, wasModified }
}

/**
 * 生成完整 HTML 文档（用于 iframe 预览和存储）
 * 平台提供固定的 head 部分，LLM 只提供 body 内容
 */
export function wrapInFullHtml(bodyContent: string, name: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';">
<title>${name}</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>
tailwind.config = {
  theme: {
    extend: {
      colors: {
        primary: '#8B1A1A',
        accent: '#D4A843',
        surface: '#141414',
        background: '#0a0a0a',
      }
    }
  }
}
</script>
<style>
  body { background: #0a0a0a; color: #fafafa; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

/**
 * 解析 LLM 返回的 JSON 响应，提取代码
 */
export function parseLLMResponse(rawContent: string): { code: string; preview: string } | null {
  try {
    // 尝试从 markdown 代码块中提取 JSON
    const jsonMatch = rawContent.match(/```(?:json)?\s*([\s\S]*?)\s*```/)
    const jsonStr = jsonMatch ? jsonMatch[1] : rawContent

    const parsed = JSON.parse(jsonStr)

    // 支持两种格式：{code: [{filename, content}]} 或 {content: string}
    if (parsed.code && Array.isArray(parsed.code) && parsed.code[0]?.content) {
      return { code: parsed.code[0].content, preview: parsed.preview_html || parsed.code[0].content }
    }
    if (parsed.content) {
      return { code: parsed.content, preview: parsed.preview_html || parsed.content }
    }

    return null
  } catch {
    return null
  }
}
